name: fkit
description: Awesome Flutter template for project bootstraping real quick

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.1.0
  flutter_secure_storage: ^5.0.2
  geocode: ^1.0.1
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  intl: ^0.17.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_flavorizr: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

# run: flutter pub run flutter_flavorizr
flavorizr:
  app:
    android:
      flavorDimensions: "flavor"
    ios: null

  flavors:
    app One:
      app:
        name: "Example of App One"
      android:
        applicationId: "com.example.appOne"

      ios:
        bundleId: "com.example.apple"

    banana:
      app:
        name: "Banana App"

      android:
        applicationId: "com.example.banana"
      ios:
        bundleId: "com.example.banana"
